sudo: false
language: ruby
before_install: gem install bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
matrix:
  include:
    - rvm: 1.9.3
      gemfile: Gemfile.ruby-1.9.rb
    - rvm: jruby-19mode
      gemfile: Gemfile.ruby-1.9.rb
